### ISSUE TITLE
Firefox joining the Chime but page is asking for username

### ISSUE THREAD

**Issue by koxon** [aws-samples/amazon-chime-meeting-broadcast-demo#6]
The script works fine but when Firefox opens the chime meeting page, we get prompted to input a Name.
So we never get past the welcome page and we never see the videos.

**Comment by codeslinger** [comment]
What is the value of the `MEETING_URL` that you are using?

**Comment by koxon** [comment]
I was using the direct chime meeting URL. 
I will try the
"Example(Hosted Chime SDK Serverless Demo URL): <Hosted Chime URL>/?m=<Meeting ID>&broadcast=true" 

thanks !

**Comment by koxon** [comment]
It appears though that I need to deploy the meetingV2 serverless application. By default it deploys the "meeting" version which doesn't support "broadcast=true" 
I think you should mention it in the README @codeslinger

**Comment by prabhupadhayay** [comment]
I have used version -v2(meeting url) url but it always show join now page on broadcast ,where meeting conference is going on.
